# ================= APP =================
spring.application.name=btop
server.port=8080

# ================= DATASOURCE =================
spring.datasource.url=jdbc:h2:file:./data/h2Db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


# ================= H2 CONSOLE =================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ================= JPA =================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Prevent LazyInitializationException in JSON
spring.jpa.open-in-view=false

# ================= LOGGING =================
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# ================= SWAGGER =================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html